# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and push Docker image to Azure Container Registry

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY_NAME: gravercentret.azurecr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    environment:
      name: 'Production'
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_16CB276D99CB40DB9752309DBCA608A2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_93E6EA7B0E9F43BC9B4310523F9CFEB2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FC14C2B06F754714B8F8A93F7F2FC3C6 }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: |
            ${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
