# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and push Docker image to Azure Container Registry

on:
  push:
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ github.repository }}
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_DEPLOYMENT_USER_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_GRAVERCENTRET_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Login to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.ACR_GRAVERCENTRET_REGISTRY_NAME }}
          username: ${{ vars.ACR_GRAVERCENTRET_TOKEN_NAME }}
          password: ${{ secrets.ACR_GRAVERCENTRET_TOKEN_PASSWORD }}
          
      - name: Build and push as latest
        if: github.head_ref == 'main' || github.ref_name == 'main'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ vars.ACR_GRAVERCENTRET_REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:latest
            ${{ vars.ACR_GRAVERCENTRET_REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Build and push with branch name as tag
        if: github.head_ref != 'main' && github.ref_name != 'main'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ vars.ACR_GRAVERCENTRET_REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ env.BRANCH_NAME }}
            ${{ vars.ACR_GRAVERCENTRET_REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
